defmodule Fairpr.Repo.Migrations.AddStudentAndCurrentTherapist do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:students, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :first_name, :text, null: false
      add :middle_initial, :text
      add :last_name, :text, null: false
      add :birthday, :date, null: false
      add :intake_date, :date, null: false
      add :discharge_date, :date
      add :intake_grade, :bigint, null: false
      add :current_grade, :bigint, null: false
      add :handle, :text, null: false

      add :current_therapist_id,
          references(:users,
            column: :id,
            name: "students_current_therapist_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:students, [:handle], name: "students_unique_handle_index")

    create unique_index(:students, [:first_name, :last_name, :birthday],
             name: "students_unique_name_and_birthday_index"
           )
  end

  def down do
    drop constraint(:students, "students_current_therapist_id_fkey")

    drop_if_exists unique_index(:students, [:first_name, :last_name, :birthday],
                     name: "students_unique_name_and_birthday_index"
                   )

    drop_if_exists unique_index(:students, [:handle], name: "students_unique_handle_index")

    drop table(:students)
  end
end
