defmodule Fairpr.Repo.Migrations.AddUserNameFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :first_name, :text
      add :middle_initial, :text
      add :last_name, :text
    end

    execute "UPDATE users SET first_name = '' WHERE first_name IS NULL"
    execute "UPDATE users SET last_name = '' WHERE last_name IS NULL"

    alter table(:users) do
      modify :first_name, :text, null: false
      modify :last_name, :text, null: false
    end
  end

  def down do
    alter table(:users) do
      modify :first_name, :text, null: true
      modify :last_name, :text, null: true
    end

    alter table(:users) do
      remove :last_name
      remove :middle_initial
      remove :first_name
    end
  end
end
