defmodule Fairpr.Repo.Migrations.AddRolesUserRolesAndMaximumStudents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :maximum_students, :bigint, null: false, default: 0
    end

    create table(:user_roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "user_roles_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :role_id, :uuid, null: false
    end

    create unique_index(:user_roles, [:user_id, :role_id],
             name: "user_roles_unique_user_role_index"
           )

    create table(:roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:user_roles) do
      modify :role_id,
             references(:roles,
               column: :id,
               name: "user_roles_role_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:roles) do
      add :name, :text, null: false
    end

    create unique_index(:roles, [:name], name: "roles_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:roles, [:name], name: "roles_unique_name_index")

    alter table(:roles) do
      remove :name
    end

    drop constraint(:user_roles, "user_roles_role_id_fkey")

    alter table(:user_roles) do
      modify :role_id, :uuid
    end

    drop table(:roles)

    drop constraint(:user_roles, "user_roles_user_id_fkey")

    drop_if_exists unique_index(:user_roles, [:user_id, :role_id],
                     name: "user_roles_unique_user_role_index"
                   )

    drop table(:user_roles)

    alter table(:users) do
      remove :maximum_students
    end
  end
end
